name: Sync docs for GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'web/pyorankulmat.html'
      - 'web/favicon.png'
      - '.github/workflows/sync-docs.yml'

permissions:
  contents: write

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy app to docs
        run: |
          mkdir -p docs
          cp web/pyorankulmat.html docs/pyorankulmat.html
          if [ -f web/favicon.png ]; then cp web/favicon.png docs/favicon.png; fi
          # Keep a simple index that redirects to the app (if not present)
          if [ ! -f docs/index.html ]; then
            echo '<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=pyorankulmat.html">' > docs/index.html
          fi
          # Ensure Jekyll is disabled and config exists
          touch docs/.nojekyll
          if [ ! -f docs/_config.yml ]; then
            printf 'theme: null\nplugins: []\n' > docs/_config.yml
          fi

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: sync docs for GitHub Pages'
          file_pattern: docs/*

